[dev]
framework = "#static"
command = "npx @11ty/eleventy --input=src --quiet --watch"

[build]
command = "npx @11ty/eleventy --input=src"
publish = "_site"

[[edge_functions]]
function = "forms"
path = "/forms/"

[[edge_functions]]
function = "repeat"
path = "/*"

[[edge_functions]]
function = "dark-mode"
path = "/appearance/"

[[edge_functions]]
function = "eleventy-edge"
path = "/*"